test:
  adapter: postgresql
  username: postgres
  password:
  database: bookmark_manager_test
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5432
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>


development:
  <<: *defaults

production:
  <<: *defaults
